[tool.poetry]
name = "tap-typeform"
version = "0.0.1"
description = "`tap-typeform` is a Singer tap for Typeform, built with the Meltano SDK for Singer Taps."
authors = ["Albert Marrero"]
keywords = [
    "ELT",
    "Typeform",
]
license = "Apache 2.0"

[tool.poetry.dependencies]
python = ">=3.10,<3.14"
requests = "^2.31.0"
singer-sdk = "^0.40.0"

[tool.poetry.dev-dependencies]
pytest = "^8.0.0"
tox = "^4.0.0"
flake8 = "^7.0.0"
black = "^24.0.0"
pydocstyle = "^6.3.0"
mypy = "^1.8.0"
types-requests = "^2.31.0"

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"

[tool.poetry.scripts]
# CLI declaration
tap-typeform = 'tap_typeform.tap:TapTypeform.cli'
